// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: report.proto

package api

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReportCollectorClient is the client API for ReportCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportCollectorClient interface {
	ReceiveReport(ctx context.Context, in *ReportBody, opts ...grpc.CallOption) (*ReportAccept, error)
}

type reportCollectorClient struct {
	cc grpc.ClientConnInterface
}

func NewReportCollectorClient(cc grpc.ClientConnInterface) ReportCollectorClient {
	return &reportCollectorClient{cc}
}

func (c *reportCollectorClient) ReceiveReport(ctx context.Context, in *ReportBody, opts ...grpc.CallOption) (*ReportAccept, error) {
	out := new(ReportAccept)
	err := c.cc.Invoke(ctx, "/report.ReportCollector/ReceiveReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportCollectorServer is the server API for ReportCollector service.
// All implementations must embed UnimplementedReportCollectorServer
// for forward compatibility
type ReportCollectorServer interface {
	ReceiveReport(context.Context, *ReportBody) (*ReportAccept, error)
	mustEmbedUnimplementedReportCollectorServer()
}

// UnimplementedReportCollectorServer must be embedded to have forward compatible implementations.
type UnimplementedReportCollectorServer struct {
}

func (UnimplementedReportCollectorServer) ReceiveReport(context.Context, *ReportBody) (*ReportAccept, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveReport not implemented")
}
func (UnimplementedReportCollectorServer) mustEmbedUnimplementedReportCollectorServer() {}

// UnsafeReportCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportCollectorServer will
// result in compilation errors.
type UnsafeReportCollectorServer interface {
	mustEmbedUnimplementedReportCollectorServer()
}

func RegisterReportCollectorServer(s grpc.ServiceRegistrar, srv ReportCollectorServer) {
	s.RegisterService(&ReportCollector_ServiceDesc, srv)
}

func _ReportCollector_ReceiveReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportCollectorServer).ReceiveReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.ReportCollector/ReceiveReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportCollectorServer).ReceiveReport(ctx, req.(*ReportBody))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportCollector_ServiceDesc is the grpc.ServiceDesc for ReportCollector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportCollector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "report.ReportCollector",
	HandlerType: (*ReportCollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveReport",
			Handler:    _ReportCollector_ReceiveReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report.proto",
}
